import sidebarEn from '../sidebars/blog.sidebar.en'
import { generateNavThemes } from '../theme/background/themes';

export default {
  lang: 'en',
  description: "HolyBear's personal site, featuring HyperOS modules, tech notes, and Android customization & open-source sharing.",
  themeConfig: {
    nav: [
      { text: 'Blog', link: '/en/blog/' },
      { text: 'Portfolio', link: '/en/Mod' },
      { text: 'Shortlink', link: 'https://go.holybear.tw/' },
      { text: 'Donate', link: 'https://paypal.me/holybear0610' },
      { 
        text: 'Themes', 
        items: generateNavThemes()
      }
    ],
    sidebar: {
      '/en/blog/': sidebarEn
    },
    sidebarMenuLabel: 'Blog List',
    returnToTopLabel: 'Return to top',
    darkModeSwitchLabel: 'Dark mode',
    outline: {
      label: 'Outline'
    },
    docFooter: {
      prev: 'Previous',
      next: 'Next'
    },
    lastUpdated: {
      text: 'Last updated',
      formatOptions: {
        dateStyle: 'medium' as const,
        timeStyle: 'short' as const,
        hour12: false
      }
    },
    editLink: {
      pattern: 'https://github.com/HolyBearTW/holybear.tw/edit/main/:path',
      text: 'Edit this page on GitHub'
    },
    footer: {
      message: 'AGPL-3.0 Licensed',
      copyright: 'Copyright © 2025 HolyBear'
    },
    notFound: {
      title: 'Page Not Found',
      quote: "Looks like you're lost?",
      linkLabel: 'Back to Home',
      linkText: 'Return Home'
    },
    search: {
      provider: 'algolia' as const,
      options: {
        placeholder: 'Search articles',
        translations: {
          button: {
            buttonText: 'Search',
            buttonAriaLabel: 'Search'
          },
          modal: {
            searchBox: {
              clearButtonTitle: 'Clear search',
              clearButtonAriaLabel: 'Clear search',
              closeButtonText: 'Cancel',
              closeButtonAriaLabel: 'Cancel',
              placeholderText: 'Search articles',
              placeholderTextAskAi: 'Ask AI: ',
              placeholderTextAskAiStreaming: 'Answering...',
              searchInputLabel: 'Search',
              backToKeywordSearchButtonText: 'Back to keyword search',
              backToKeywordSearchButtonAriaLabel: 'Back to keyword search'
            },
            startScreen: {
              recentSearchesTitle: 'Recent Searches',
              noRecentSearchesText: 'No recent searches',
              saveRecentSearchButtonTitle: 'Save to recent searches',
              removeRecentSearchButtonTitle: 'Remove from recent searches',
              favoriteSearchesTitle: 'Favorites',
              removeFavoriteSearchButtonTitle: 'Remove from favorites',
              recentConversationsTitle: 'Recent Conversations',
              removeRecentConversationButtonTitle: 'Remove conversation from history'
            },
            errorScreen: {
              titleText: 'Unable to fetch results',
              helpText: 'You might need to check your network connection'
            },
            noResultsScreen: {
              noResultsText: 'No results found',
              suggestedQueryText: 'You can try searching for',
              reportMissingResultsText: 'Think there should be results?',
              reportMissingResultsLinkText: 'Let us know'
            },
            resultsScreen: {
              askAiPlaceholder: 'Ask AI: '
            },
            askAiScreen: {
              disclaimerText: 'Answers are generated by AI and may be inaccurate. Please verify on your own.',
              relatedSourcesText: 'Related sources',
              thinkingText: 'Thinking...',
              copyButtonText: 'Copy',
              copyButtonCopiedText: 'Copied!',
              copyButtonTitle: 'Copy',
              likeButtonTitle: 'Like',
              dislikeButtonTitle: 'Dislike',
              thanksForFeedbackText: 'Thanks for your feedback!',
              preToolCallText: 'Searching...',
              duringToolCallText: 'Searching ',
              afterToolCallText: 'searched'
            },
            footer: {
              selectText: 'Select',
              submitQuestionText: 'Submit question',
              selectKeyAriaLabel: 'Enter key',
              navigateText: 'Navigate',
              navigateUpKeyAriaLabel: 'Up arrow',
              navigateDownKeyAriaLabel: 'Down arrow',
              closeText: 'Close',
              backToSearchText: 'Back to search',
              closeKeyAriaLabel: 'Esc key',
              poweredByText: 'Powered by'
            }
          }
        }
      }
    }
  }
}
